2022/10/18 17:40:19 [error] 948#948: *7 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:44:39 [error] 948#948: *10 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:44:45 [error] 948#948: *10 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Request.php:299
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}
$_SERVER = [
    'USER' => 'www-data',
    'HOME' => '/var/www',
    'HTTP_ACCEPT_LANGUAGE' => 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7'," while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:46:00 [error] 948#948: *14 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:46:02 [error] 948#948: *14 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:46:04 [error] 948#948: *14 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:48:11 [error] 948#948: *21 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:51:03 [error] 948#948: *24 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "site/index". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.p" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:51:04 [error] 948#948: *24 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "site/index". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.p" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:53:04 [error] 948#948: *28 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 17:54:43 [error] 948#948: *31 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 18:03:22 [error] 948#948: *34 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 18:10:49 [error] 948#948: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/www/pad/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#1 /var/www/pad/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#2 /var/www/pad/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/pad/vendor/yiisoft/yii2/web/Application.php:115
Sta" while reading upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1"
2022/10/18 20:54:26 [error] 948#948: *227 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Class "yii\bootstrap5\BootstrapAsset" does not exist in /var/www/pad/vendor/yiisoft/yii2/di/Container.php:507
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#1 /var/www/pad/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#2 /var/www/pad/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#3 /var/www/pad/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#4 /var/www/pad/vendor/yiisoft/yii2/web/AssetManager.php(292): yii\BaseYii::createObject()
#5 /var/www/pad/vendor/yiisoft/yii2/web/AssetManager.php(265): yii\web\AssetManager->loadBundle()
#6 /var/www/pad/vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#7 /var/www/pad/vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#8 /var/www/pad/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetB" while reading upstream, client: 127.0.0.1, server: _, request: "GET /signin HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/signin"
2022/10/18 20:55:58 [error] 948#948: *230 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Class "yii\bootstrap5\BootstrapAsset" does not exist in /var/www/pad/vendor/yiisoft/yii2/di/Container.php:507
Stack trace:
#0 /var/www/pad/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#1 /var/www/pad/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#2 /var/www/pad/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#3 /var/www/pad/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#4 /var/www/pad/vendor/yiisoft/yii2/web/AssetManager.php(292): yii\BaseYii::createObject()
#5 /var/www/pad/vendor/yiisoft/yii2/web/AssetManager.php(265): yii\web\AssetManager->loadBundle()
#6 /var/www/pad/vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#7 /var/www/pad/vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#8 /var/www/pad/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetB" while reading upstream, client: 127.0.0.1, server: _, request: "GET /signin HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/signin"
